name: 1.0.$(Rev:r)

trigger:
- master

pr:
  - master
  - development

stages:
  - stage: Build
    jobs: 
      - job: Preview

        pool:
          vmImage: 'ubuntu-latest'

        steps:
        - script: echo Hello, world! Test
          displayName: 'Run a one-line script'

        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'

        - script: exit 0
          displayName: 'Fixed this task'

        - script: |
            echo 'Fixed it!'
            exit 0
          displayName: 'New task'
