name: 1.0.$(Rev:r)

trigger:
- master

pr:
  - master
  - development

stages:
  - stage: Build
    jobs: 
      - job: Preview

        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: Pulumi@1
            condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'))
            inputs:
              azureSubscription: 'My Service Connection'
              command: 'preview'
              cwd: 'pulumi-devops-pipeline/stack'
              stack: 'jamesrcounts/AzureCSharp.DevOpsPipeline/azcs-devopspipeline-dev'
